[workspace]
members = ["cw-orch", "packages/*", "contracts/*"]
version = "0.13.1"
resolver = "2"

[workspace.package]
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrator"
version = "0.13.1"

[workspace.dependencies]
cosmwasm-std = { version = "1.1" }
cw-multi-test = { version = "0.16.4" }
cw-remote-test = { package = "cw-multi-test", git = "https://github.com/Kayanski/cw-multi-test/", branch = "adapt_for_local_execution" }
anyhow = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
