[package]
name = "cw-orch-starship"
version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonpath-rust = "0.3.0"
reqwest = { version = "0.11.18", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.102"
ibc-chain-registry = { workspace = true }
ibc-relayer-types = { workspace = true }
thiserror = "1.0.43"
serde_yaml = "0.9"
cosmwasm-std = "1.2.7"
cw-orch-environment = { workspace = true }
