[package]
name = "cw-orch-interchain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-starship = { workspace = true }
cw-orch-daemon = { workspace = true }
cw-orch-environment = { workspace = true }


anyhow.workspace = true
async-recursion = "1.0.4"
base64 = "0.21.2"
cosmwasm-schema = "1.3.1"
futures = "0.3.28"
ibc-chain-registry = { workspace = true }
ibc-relayer-types = { workspace = true }
log = "0.4.19"
log4rs = "1.2.0"
thiserror = "1.0.44"
tokio = "1.29.1"
tonic = "0.9.2"
cosmrs = "0.14.0"
futures-util = "0.3.28"
derive_builder = "0.12.0"
diff-struct = "0.5.3"
serde_json.workspace = true
